### ISSUE TITLE
challenge_hash_input bug

### ISSUE THREAD

**Issue by luffyz** [yuri-gushin/Roboo#1]
challenge_hash_input does not work when we pass something unique to a user like an IP address. It passes random IPs from other users instead of the user's actual IP. Hence the page keeps refreshing to generate another cookie instead of waiting for the validity_window time

**Comment by luffyz** [comment]
btw a simple fix if you want to use the user's IP to generate cookie

change this line

$valid_cookie = generate_cookie($settings->{challenge_hash_input}, get_secret());

to this

$valid_cookie = generate_cookie($request->remote_addr, get_secret());

**Comment by alexbhr** [comment]
Thanks for reporting this, we will look at it soon. Also, please feel free to submit patches ;)
