### ISSUE TITLE
Bug for white space and " in POST body

### ISSUE THREAD

**Issue by fornex** [yuri-gushin/Roboo#3]
If a client sends a POST request, which has to be challenged and request_body contains spaces (url encoded in +), then Roboo will treat:
- %2B
- +
- whitespaces

in the same way, which will messup the whitespaces in the submitted form.

The same happens to the double quotes in the request_body, which break the challenge form, like this:

<form name="response" method="post">
<input type="hidden" name="param1" value="value1">
<input type="hidden" name="param2" value="val"ue2">
</form>

**Comment by fornex** [comment]
```<form name="response" method="post">
<input type="hidden" name="param1" value="value1">
<input type="hidden" name="param2" value="val"ue2">
</form>

```
```

**Comment by fornex** [comment]
if the posted form contains name="submit", then the default javascript will fail on the: document.response.submit()

**Comment by fornex** [comment]
if the POST body contains a file (Content-Disposition), then obviously Roboo will fail to send the data after verification.

**Comment by yuri-gushin** [comment]
Thanks for reporting these in!

The submit() issue is a good spot, the double-quotes as well.

About the whitespace decoding - could you provide an example POST request that can demonstrate the issue of treating whitespaces, + and %2B identically?

**Comment by FraDiavolo** [comment]
I have the same problem. I use nginx with roboo as frontend and litespeed with phpbb3 as backend.

There are two posting options in phpBB3: "Reply" & "Quick reply".

When the cookie is timed out, a "Reply" will reopen the form and the text is gone. A "Quick reply" generates this:
Lorem+ipsum+dolor+sit+amet,+consetetur+sadipscing+elitr

I have installed a demo installation for you. Please let me know if you want access.

THX

**Comment by yuri-gushin** [comment]
Please email me directly with details of how to access your demo installation and I'll test it out
