### ISSUE TITLE
Nginx wont start

### ISSUE THREAD

**Issue by Anti-Hack** [yuri-gushin/Roboo#4]
After I have compiled nginx and changed the configuration to default Roboo config, nginx wont start. I have installed alle Perl Modules and compiled nginx with perl support. There are no Errors in my logs.

OS: Debian 64bit

**Comment by yuri-gushin** [comment]
So default nginx config works - yet default Roboo config (nginx-conf-example) does not work?
Have you tried running diff between the two and spot any immediate quirks?
Are the paths set correctly (e.g. perl_modules, proxy_cache_path)?  Is Roboo.pm in the path of perl_modules?

Try sending an HTTP request after ensuring the above is okay, and paste the output of the error log in case it doesn't work

**Comment by Anti-Hack** [comment]
All these settings are correct. But now it takes between 10 - 20 minutes to start nginx. Then everything is fine but on next start - same problem

and yes, default config works.

######
i compiled without:

  --without-http_autoindex_module \
  --without-http_browser_module \
  --without-http_empty_gif_module \
  --without-http_fastcgi_module \
  --without-http_geo_module \
  --without-http_map_module \
  --without-http_memcached_module \
  --without-http_referer_module \
  --without-http_scgi_module \
  --without-http_split_clients_module \
  --without-http_ssi_module \
  --without-http_userid_module \
  --without-http_uwsgi_module \

**Comment by yuri-gushin** [comment]
How do you notice that it "takes 10-20 minutes"?
Do you send an HTTP request and it times out?

In the default config, if you switch 'perl Roboo::handler;' for 'proxy_pass http://yoursite.com;' - does the problem go away and all requests are proxied to your site immediately?

**Comment by Anti-Hack** [comment]
> In the default config, if you switch 'perl Roboo::handler;' for 'proxy_pass http://yoursite.com;' - does the problem go away and all > > > requests are proxied to your site immediately?

That works

> How do you notice that it "takes 10-20 minutes"?
> Do you send an HTTP request and it times out?

I try it every 3 minutes with curl

**Comment by yuri-gushin** [comment]
Please run this and provide the output - time perl -M'Crypt::Random qw(makerandom_octet)' -e 'makerandom_octet(Length => 64, Strength => 1)'

I'm thinking your /dev/random pool is low and it takes Roboo a long time to generate a secret initially, but after it does so - everything works as expected.

**Comment by Anti-Hack** [comment]
time perl -M'Crypt::Random qw(makerandom_octet)' -e 'makerandom_octet(Length => 64, Strength => 1)'

real    4m36.506s
user    0m0.024s
sys     0m0.004s

you are right Oo do u know how to fix?

**Comment by yuri-gushin** [comment]
You can easily fix this by changing line 152 in Roboo.pm to say "Strength => 0" instead of 1.

Let me know if this fixes the issue.

**Comment by Anti-Hack** [comment]
Yes that works :)

Thanks you
