### ISSUE TITLE
Use of uninitialized value in split

### ISSUE THREAD

**Issue by divxcentral** [yuri-gushin/Roboo#5]
I am having an error of "Use of uninitialized value in split at /usr/local/share/nginx/Roboo.pm line 269."
From my observation I concluded that error message is only shown then a new client is trying to establish connection and was not allowed to pass through gateway. It is not so critical, but performance will be a bit better if we could get rid of that message. Any help or point me in the right direction would be extremely grateful.

**Comment by yuri-gushin** [comment]
Can you paste the full request that triggers this? Do you have POST requests that contain zero data (seems like it could trigger such behavior)?

**Comment by divxcentral** [comment]
Unfortunately I cannot correlate the error message with a record in access log because the error message appears in error log without time stamp. Maybe you could tell me how to enable time stamp for error messages in Roboo.pm?

**Comment by yuri-gushin** [comment]
Try adding this to line 265:

<code>return '' unless (defined $body);</code>

Does this fix it?

**Comment by divxcentral** [comment]
It looks like it helps. I will keep an eye on this and let you know if something changed. Thank you so much!

P.S. I am also getting very rare message that you can see below, probably because Roboo does not support IPv6 yet.

```
Argument "2001:240:2200:1e00:20c:29ff:fe95:b817" isn't numeric in pack at /usr/lib/perl5/site_perl/5.8.8/Net/IP/Match/Regexp.pm line 234.                                                     
Character in 'C' format wrapped in pack at /usr/lib/perl5/site_perl/5.8.8/Net/IP/Match/Regexp.pm line 234.                                                                                    
Argument "2001:240:2200:1e00:20c:29ff:fe8a:c63d" isn't numeric in pack at /usr/lib/perl5/site_perl/5.8.8/Net/IP/Match/Regexp.pm line 234.                                                     
Character in 'C' format wrapped in pack at /usr/lib/perl5/site_perl/5.8.8/Net/IP/Match/Regexp.pm line 234. 
```

**Comment by yuri-gushin** [comment]
Sure thing - I'll close this ticket & commit the code

About IPv6 - you're right, Roboo doesn't officially support it for now - it should still work in IPv6 environments but it wasn't really tested or developed for it (to be specific, it's the underlying module Roboo uses that doesn't support it).  Feel free to open a new ticket for IPv6 support, and better yet, submit code :)
